# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quantif.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_quantif_wid(object):
    def setupUi(self, quantif_wid):
        quantif_wid.setObjectName("quantif_wid")
        quantif_wid.resize(565, 530)
        quantif_wid.setMinimumSize(QtCore.QSize(379, 530))
        quantif_wid.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Peru))
        quantif_wid.setWizardStyle(QtWidgets.QWizard.ModernStyle)
        quantif_wid.setOptions(QtWidgets.QWizard.HelpButtonOnRight|QtWidgets.QWizard.NoBackButtonOnLastPage|QtWidgets.QWizard.NoBackButtonOnStartPage)
        quantif_wid.setTitleFormat(QtCore.Qt.RichText)
        quantif_wid.setSubTitleFormat(QtCore.Qt.RichText)
        self.startpage = QtWidgets.QWizardPage()
        self.startpage.setMinimumSize(QtCore.QSize(362, 0))
        self.startpage.setObjectName("startpage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.startpage)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.startpage)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.equlay = QtWidgets.QVBoxLayout()
        self.equlay.setObjectName("equlay")
        self.enlabel = QtWidgets.QLabel(self.groupBox_2)
        self.enlabel.setObjectName("enlabel")
        self.equlay.addWidget(self.enlabel)
        self.effabel = QtWidgets.QLabel(self.groupBox_2)
        self.effabel.setObjectName("effabel")
        self.equlay.addWidget(self.effabel)
        self.verticalLayout_3.addLayout(self.equlay)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.eff_default = QtWidgets.QPushButton(self.groupBox)
        self.eff_default.setAutoDefault(False)
        self.eff_default.setObjectName("eff_default")
        self.horizontalLayout_2.addWidget(self.eff_default)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.groupBox)
        quantif_wid.addPage(self.startpage)
        self.nuclidepage = QtWidgets.QWizardPage()
        self.nuclidepage.setObjectName("nuclidepage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.nuclidepage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.nuclidepage)
        self.label_4.setMinimumSize(QtCore.QSize(150, 150))
        self.label_4.setMaximumSize(QtCore.QSize(150, 150))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("icons/tc45_3.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.nuclidepage)
        self.label_5.setMinimumSize(QtCore.QSize(184, 0))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.nuclide_lay = QtWidgets.QVBoxLayout()
        self.nuclide_lay.setObjectName("nuclide_lay")
        self.horizontalLayout_4.addLayout(self.nuclide_lay)
        self.nuclide_label = QtWidgets.QLabel(self.nuclidepage)
        self.nuclide_label.setText("")
        self.nuclide_label.setObjectName("nuclide_label")
        self.horizontalLayout_4.addWidget(self.nuclide_label)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.radioButton = QtWidgets.QRadioButton(self.nuclidepage)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_5.addWidget(self.radioButton)
        quantif_wid.addPage(self.nuclidepage)
        self.manualpage = QtWidgets.QWizardPage()
        self.manualpage.setObjectName("manualpage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.manualpage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.manualpage)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton)
        self.toolButton = QtWidgets.QToolButton(self.manualpage)
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout_4.addWidget(self.toolButton)
        self.listView = QtWidgets.QListView(self.manualpage)
        self.listView.setObjectName("listView")
        self.verticalLayout_4.addWidget(self.listView)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        quantif_wid.addPage(self.manualpage)
        self.areapage = QtWidgets.QWizardPage()
        self.areapage.setObjectName("areapage")
        quantif_wid.addPage(self.areapage)
        self.endpage = QtWidgets.QWizardPage()
        self.endpage.setObjectName("endpage")
        quantif_wid.addPage(self.endpage)

        self.retranslateUi(quantif_wid)
        QtCore.QMetaObject.connectSlotsByName(quantif_wid)

    def retranslateUi(self, quantif_wid):
        _translate = QtCore.QCoreApplication.translate
        quantif_wid.setWindowTitle(_translate("quantif_wid", "Análisis y Cuantificación"))
        self.startpage.setTitle(_translate("quantif_wid", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Análisis y Cuantificación de Muestras de Aire</span></p></body></html>"))
        self.startpage.setSubTitle(_translate("quantif_wid", " "))
        self.groupBox.setTitle(_translate("quantif_wid", "Importante"))
        self.label_3.setText(_translate("quantif_wid", "<html><head/><body><p align=\"justify\">A continuación se muestran los datos de calibración de energías y eficiencia.</p><p align=\"justify\">Verificar que estos datos en correctos. </p><p align=\"justify\">En caso esten incorrectos o estén incompletos, se recomienda realizar primero la calibración.</p><p align=\"justify\">Se puede utilizar el botón &quot;Eficiencia por defecto&quot; para cargar automáticamente el archivo por defecto de calibración de eficiencia para una fuente de tipo &quot;Filtro de Aire TC-45&quot; en posición estándar dentro del blindaje.                                                                                                      </p></body></html>"))
        self.groupBox_2.setTitle(_translate("quantif_wid", "Curvas de Calibración"))
        self.enlabel.setText(_translate("quantif_wid", "Energía: "))
        self.effabel.setText(_translate("quantif_wid", "Eficiencia:"))
        self.eff_default.setText(_translate("quantif_wid", "Eficiencia por defecto"))
        self.nuclidepage.setTitle(_translate("quantif_wid", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Análisis y Cuantificación de Muestras de Aire</span></p></body></html>"))
        self.nuclidepage.setSubTitle(_translate("quantif_wid", "<html><head/><body><p><span style=\" font-size:10pt;\">Elección de Radioisótopo</span></p></body></html>"))
        self.label_5.setText(_translate("quantif_wid", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Análisis y Cuantificación de Muestras de Aire</span></p><p><span style=\" font-size:10pt;\">Elección de Radioisótopo</span></p></body></html>"))
        self.radioButton.setText(_translate("quantif_wid", "RadioButton"))
        self.pushButton.setText(_translate("quantif_wid", "PushButton"))
        self.toolButton.setText(_translate("quantif_wid", "..."))
