file_number: 5
nuclide_file : config/nuclides.yml
dataFolder : files
color : blue
brand : ford
city: new york
cabriolet:
    color : black
    engine:
        cylinders : 8
        placement : mid
    doors : 2